/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulacion_mensario;

/**
 *
 * @author adrys
 */
public class Envios extends javax.swing.JFrame {

    /**
     * Creates new form Envios
     */
    public Envios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreUsr = new javax.swing.JLabel();
        lblNombreRemitente = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombreRemitente = new javax.swing.JTextField();
        IFDestinatario = new javax.swing.JInternalFrame();
        lblMoviles = new javax.swing.JLabel();
        jScrollPaneMoviles = new javax.swing.JScrollPane();
        txtAreaMoviles = new javax.swing.JTextArea();
        lblContador = new javax.swing.JLabel();
        btnAñadirMovil = new javax.swing.JButton();
        btnEliminarMoviles = new javax.swing.JButton();
        IFMensaje = new javax.swing.JInternalFrame();
        lblTexto = new javax.swing.JLabel();
        jScrollPaneTexto = new javax.swing.JScrollPane();
        txtAreaMensaje = new javax.swing.JTextArea();
        lblNumMensajes = new javax.swing.JLabel();
        lblNumCaracteres = new javax.swing.JLabel();
        btnEliminarTexto = new javax.swing.JButton();
        CheckEnvioProgramado = new javax.swing.JCheckBox();
        lblHoraEnvio = new javax.swing.JLabel();
        txtHoraEnvio = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        lblSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 720));

        lblNombreUsr.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombreUsr.setText("NombreUsr(KFSJS123FKSL5LG32)");
        lblNombreUsr.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Esta utilizando la licencia:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 11))); // NOI18N

        lblNombreRemitente.setText("Nombre de remitente:");

        IFDestinatario.setTitle("Destianatario");
        IFDestinatario.setVisible(true);

        lblMoviles.setText("Móviles:");

        txtAreaMoviles.setColumns(20);
        txtAreaMoviles.setRows(5);
        jScrollPaneMoviles.setViewportView(txtAreaMoviles);

        lblContador.setText("Número de moviles insertados: 0");

        btnAñadirMovil.setText("Añadir movil");
        btnAñadirMovil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnEliminarMoviles.setText("Limpiar texto");
        btnEliminarMoviles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout IFDestinatarioLayout = new javax.swing.GroupLayout(IFDestinatario.getContentPane());
        IFDestinatario.getContentPane().setLayout(IFDestinatarioLayout);
        IFDestinatarioLayout.setHorizontalGroup(
            IFDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFDestinatarioLayout.createSequentialGroup()
                .addGroup(IFDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IFDestinatarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblContador, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(btnAñadirMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnEliminarMoviles, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneMoviles))
                .addContainerGap())
            .addGroup(IFDestinatarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMoviles)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IFDestinatarioLayout.setVerticalGroup(
            IFDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFDestinatarioLayout.createSequentialGroup()
                .addComponent(lblMoviles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneMoviles, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IFDestinatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContador)
                    .addComponent(btnAñadirMovil)
                    .addComponent(btnEliminarMoviles))
                .addGap(5, 5, 5))
        );

        IFMensaje.setTitle("Mensaje");
        IFMensaje.setVisible(true);

        lblTexto.setText("Texto:");

        txtAreaMensaje.setColumns(20);
        txtAreaMensaje.setRows(5);
        jScrollPaneTexto.setViewportView(txtAreaMensaje);

        lblNumMensajes.setText("Número de mensajes: 1");

        lblNumCaracteres.setText("Número de caracteres: 0");

        btnEliminarTexto.setText("Limpiar texto");
        btnEliminarTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout IFMensajeLayout = new javax.swing.GroupLayout(IFMensaje.getContentPane());
        IFMensaje.getContentPane().setLayout(IFMensajeLayout);
        IFMensajeLayout.setHorizontalGroup(
            IFMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneTexto)
            .addGroup(IFMensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IFMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IFMensajeLayout.createSequentialGroup()
                        .addComponent(lblNumMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblNumCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IFMensajeLayout.createSequentialGroup()
                        .addComponent(lblTexto)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        IFMensajeLayout.setVerticalGroup(
            IFMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IFMensajeLayout.createSequentialGroup()
                .addComponent(lblTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(IFMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumMensajes)
                    .addComponent(lblNumCaracteres)
                    .addComponent(btnEliminarTexto))
                .addGap(5, 5, 5))
        );

        CheckEnvioProgramado.setText("Envio programado");

        lblHoraEnvio.setText("Hora de envio:");

        btnEnviar.setText("Enviar");
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSaldo.setText("Saldo disponible: 20.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IFDestinatario)
            .addComponent(jSeparator1)
            .addComponent(lblNombreUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(IFMensaje)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CheckEnvioProgramado, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(lblHoraEnvio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoraEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreRemitente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreRemitente, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblNombreUsr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRemitente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreRemitente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IFDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IFMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckEnvioProgramado)
                    .addComponent(lblHoraEnvio)
                    .addComponent(txtHoraEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Envios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Envios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Envios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Envios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Envios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckEnvioProgramado;
    private javax.swing.JInternalFrame IFDestinatario;
    private javax.swing.JInternalFrame IFMensaje;
    private javax.swing.JButton btnAñadirMovil;
    private javax.swing.JButton btnEliminarMoviles;
    private javax.swing.JButton btnEliminarTexto;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JScrollPane jScrollPaneMoviles;
    private javax.swing.JScrollPane jScrollPaneTexto;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblHoraEnvio;
    private javax.swing.JLabel lblMoviles;
    private javax.swing.JLabel lblNombreRemitente;
    private javax.swing.JLabel lblNombreUsr;
    private javax.swing.JLabel lblNumCaracteres;
    private javax.swing.JLabel lblNumMensajes;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JTextArea txtAreaMensaje;
    private javax.swing.JTextArea txtAreaMoviles;
    private javax.swing.JTextField txtHoraEnvio;
    private javax.swing.JTextField txtNombreRemitente;
    // End of variables declaration//GEN-END:variables
}
