/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulacion_mensario;

import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;

/**
 *
 * @author Adrián Rodríguez Sanisidro
 */
public class NuevaColumna extends javax.swing.JFrame {

    /**
     * Creates new form NuevaColumna
     */
    public NuevaColumna() {
        initComponents();
        this.setLocationRelativeTo(null);//Centra la ventana.
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));//Añade un icono a la ventana.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNuevaColumna = new javax.swing.JPanel();
        lblNombreNuevaColumna = new javax.swing.JLabel();
        txtNombreNuevaColumna = new javax.swing.JTextField();
        btnAceptarNuevaColumna = new javax.swing.JButton();
        btnCancelarNuevaColumna = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 204));

        panelNuevaColumna.setBackground(new java.awt.Color(153, 255, 255));

        lblNombreNuevaColumna.setBackground(new java.awt.Color(0, 102, 204));
        lblNombreNuevaColumna.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreNuevaColumna.setText("Nombre de la nueva columna:");

        txtNombreNuevaColumna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreNuevaColumnaKeyTyped(evt);
            }
        });

        btnAceptarNuevaColumna.setBackground(new java.awt.Color(153, 255, 255));
        btnAceptarNuevaColumna.setForeground(new java.awt.Color(0, 153, 0));
        btnAceptarNuevaColumna.setIcon(new javax.swing.ImageIcon("C:\\Users\\adrys\\Documents\\NetBeansProjects\\Simulacion_Mensario\\iconos\\rsz_check.png")); // NOI18N
        btnAceptarNuevaColumna.setText("Aceptar");
        btnAceptarNuevaColumna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarNuevaColumnaMouseClicked(evt);
            }
        });

        btnCancelarNuevaColumna.setBackground(new java.awt.Color(153, 255, 255));
        btnCancelarNuevaColumna.setForeground(new java.awt.Color(255, 0, 0));
        btnCancelarNuevaColumna.setIcon(new javax.swing.ImageIcon("C:\\Users\\adrys\\Documents\\NetBeansProjects\\Simulacion_Mensario\\iconos\\cancel.png")); // NOI18N
        btnCancelarNuevaColumna.setText("Cancelar");
        btnCancelarNuevaColumna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarNuevaColumnaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelNuevaColumnaLayout = new javax.swing.GroupLayout(panelNuevaColumna);
        panelNuevaColumna.setLayout(panelNuevaColumnaLayout);
        panelNuevaColumnaLayout.setHorizontalGroup(
            panelNuevaColumnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevaColumnaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNuevaColumnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreNuevaColumna, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                    .addComponent(txtNombreNuevaColumna)
                    .addGroup(panelNuevaColumnaLayout.createSequentialGroup()
                        .addComponent(btnAceptarNuevaColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarNuevaColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelNuevaColumnaLayout.setVerticalGroup(
            panelNuevaColumnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevaColumnaLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblNombreNuevaColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreNuevaColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(panelNuevaColumnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarNuevaColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptarNuevaColumna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNuevaColumna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNuevaColumna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    Crea una nueva columna en la tabla 'contactos',muestra la nueva tabla y crea y añade una nueva variable a la comboBox
    de las variables de los mensajes.
    */
    private void btnAceptarNuevaColumnaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarNuevaColumnaMouseClicked
        Envios.añadirColumna(txtNombreNuevaColumna.getText());
        Envios.mostrarDatosTContactos();
        Envios.mostrarVariablesCombo(Envios.comboVariablesTexto);
        this.dispose();
    }//GEN-LAST:event_btnAceptarNuevaColumnaMouseClicked
    /*
    Cierra la ventana si se cancela
    */
    private void btnCancelarNuevaColumnaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarNuevaColumnaMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarNuevaColumnaMouseClicked
    /*
    Permite teclear solo digitos,letras y borrar
    */
    private void txtNombreNuevaColumnaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreNuevaColumnaKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isAlphabetic(c) || c == KeyEvent.VK_DELETE || Character.isDigit(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreNuevaColumnaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaColumna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaColumna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaColumna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaColumna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaColumna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarNuevaColumna;
    private javax.swing.JButton btnCancelarNuevaColumna;
    private javax.swing.JLabel lblNombreNuevaColumna;
    private javax.swing.JPanel panelNuevaColumna;
    private javax.swing.JTextField txtNombreNuevaColumna;
    // End of variables declaration//GEN-END:variables
}
