/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulacion_mensario;

import com.sun.glass.events.KeyEvent;
import java.awt.Font;
import java.awt.Toolkit;
import static java.awt.event.KeyEvent.VK_SPACE;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static simulacion_mensario.CrearGrupo.empiezaPorLetra;
import static simulacion_mensario.Envios.*;

/**
 *
 * @author Adrián Rodríguez Sanisidro
 */
public class Plantilla extends javax.swing.JFrame {

    public static int eleccion;//Su valor depende si se pulsó el boton de añadir plantilla(0) o el de modificar plantilla(1).
    public static String nombreP;
    public static String textoP;
    public static boolean auxBorrado = false;

    /**
     * Creates new form Plantilla
     *
     * @param eleccion
     * @param nombreP
     * @param textoP
     */
    public Plantilla(int eleccion, String nombreP, String textoP) {
        initComponents();
        this.setLocationRelativeTo(null);//Centra la ventana
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));//Añade un icono a la ventana.
        Plantilla.eleccion = eleccion;
        Plantilla.nombreP = nombreP;
        Plantilla.textoP = textoP;
        txtNombrePlantilla.setText(nombreP);//Añade el nombre de la plantilla seleccionada(si es nueva no añade nada).
        txtAreaEscribirTextoPlantilla.setText(textoP);//Añade el texto de la plantilla seleccionada(si es nueva no añade nada).
        txtAreaEscribirTextoPlantilla.setLineWrap(true);//Añade automaticamente el salto de linea al llegar al borde.
        txtAreaEscribirTextoPlantilla.setWrapStyleWord(true);//Hace que el salto de linea no corte una palabra.
        Envios.mostrarVariablesCombo(comboVariablesPlantilla);//Añade las variables a la comboBox.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEscribirPlanilla = new javax.swing.JPanel();
        lblNombrePlantilla = new javax.swing.JLabel();
        txtNombrePlantilla = new javax.swing.JTextField();
        jScrollPaneEscribirTextoPlantilla = new javax.swing.JScrollPane();
        txtAreaEscribirTextoPlantilla = new javax.swing.JTextArea();
        btnAceptarPlantilla = new javax.swing.JButton();
        btnLimpiarTextoPlantilla = new javax.swing.JButton();
        btnLimpiarNombrePlantilla = new javax.swing.JButton();
        comboVariablesPlantilla = new javax.swing.JComboBox<>();
        btnAddVariablePlantilla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 204));

        panelEscribirPlanilla.setBackground(new java.awt.Color(153, 255, 255));
        panelEscribirPlanilla.setForeground(new java.awt.Color(255, 102, 0));

        lblNombrePlantilla.setBackground(new java.awt.Color(0, 102, 204));
        lblNombrePlantilla.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombrePlantilla.setText("Nombre de la plantilla:");

        txtNombrePlantilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombrePlantillaKeyTyped(evt);
            }
        });

        jScrollPaneEscribirTextoPlantilla.setBackground(new java.awt.Color(153, 255, 255));
        jScrollPaneEscribirTextoPlantilla.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)), "Texto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jScrollPaneEscribirTextoPlantilla.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtAreaEscribirTextoPlantilla.setColumns(20);
        txtAreaEscribirTextoPlantilla.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtAreaEscribirTextoPlantilla.setRows(5);
        jScrollPaneEscribirTextoPlantilla.setViewportView(txtAreaEscribirTextoPlantilla);

        btnAceptarPlantilla.setBackground(new java.awt.Color(153, 255, 255));
        btnAceptarPlantilla.setIcon(new javax.swing.ImageIcon("C:\\Users\\adrys\\Documents\\NetBeansProjects\\Simulacion_Mensario\\iconos\\rsz_check.jpg")); // NOI18N
        btnAceptarPlantilla.setText("Aceptar");
        btnAceptarPlantilla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptarPlantilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarPlantillaMouseClicked(evt);
            }
        });

        btnLimpiarTextoPlantilla.setBackground(new java.awt.Color(153, 255, 255));
        btnLimpiarTextoPlantilla.setIcon(new javax.swing.ImageIcon("C:\\Users\\adrys\\Documents\\NetBeansProjects\\Simulacion_Mensario\\iconos\\rsz_limpiar.png")); // NOI18N
        btnLimpiarTextoPlantilla.setToolTipText("Limpia todo el texto de la plantilla");
        btnLimpiarTextoPlantilla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarTextoPlantilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarTextoPlantillaMouseClicked(evt);
            }
        });

        btnLimpiarNombrePlantilla.setBackground(new java.awt.Color(153, 255, 255));
        btnLimpiarNombrePlantilla.setIcon(new javax.swing.ImageIcon("C:\\Users\\adrys\\Documents\\NetBeansProjects\\Simulacion_Mensario\\iconos\\rsz_limpiar.png")); // NOI18N
        btnLimpiarNombrePlantilla.setToolTipText("Limpia el nombre de la plantilla");
        btnLimpiarNombrePlantilla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarNombrePlantilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarNombrePlantillaMouseClicked(evt);
            }
        });

        comboVariablesPlantilla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "{#Nombre}", "{#País}", "{#Remitente}", "{#Teléfono}" }));

        btnAddVariablePlantilla.setBackground(new java.awt.Color(153, 255, 255));
        btnAddVariablePlantilla.setIcon(new javax.swing.ImageIcon("C:\\Users\\adrys\\Documents\\NetBeansProjects\\Simulacion_Mensario\\iconos\\add.png")); // NOI18N
        btnAddVariablePlantilla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddVariablePlantilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddVariablePlantillaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelEscribirPlanillaLayout = new javax.swing.GroupLayout(panelEscribirPlanilla);
        panelEscribirPlanilla.setLayout(panelEscribirPlanillaLayout);
        panelEscribirPlanillaLayout.setHorizontalGroup(
            panelEscribirPlanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscribirPlanillaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEscribirPlanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEscribirPlanillaLayout.createSequentialGroup()
                        .addGroup(panelEscribirPlanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneEscribirTextoPlantilla)
                            .addGroup(panelEscribirPlanillaLayout.createSequentialGroup()
                                .addComponent(lblNombrePlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombrePlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiarNombrePlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panelEscribirPlanillaLayout.createSequentialGroup()
                        .addComponent(btnAceptarPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(panelEscribirPlanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEscribirPlanillaLayout.createSequentialGroup()
                                .addComponent(comboVariablesPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddVariablePlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(238, 238, 238))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEscribirPlanillaLayout.createSequentialGroup()
                                .addComponent(btnLimpiarTextoPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        panelEscribirPlanillaLayout.setVerticalGroup(
            panelEscribirPlanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscribirPlanillaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEscribirPlanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEscribirPlanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNombrePlantilla)
                        .addComponent(txtNombrePlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLimpiarNombrePlantilla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPaneEscribirTextoPlantilla, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addGroup(panelEscribirPlanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEscribirPlanillaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelEscribirPlanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEscribirPlanillaLayout.createSequentialGroup()
                                .addGroup(panelEscribirPlanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnAddVariablePlantilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboVariablesPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24))
                            .addGroup(panelEscribirPlanillaLayout.createSequentialGroup()
                                .addComponent(btnAceptarPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(panelEscribirPlanillaLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnLimpiarTextoPlantilla))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscribirPlanilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscribirPlanilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    Permite pulsar solo letras,digitos y borrar siempre que el numero de caracteres sea menor de 64.
    */
    private void txtNombrePlantillaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombrePlantillaKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isAlphabetic(c) || Character.isDigit(c) || c == KeyEvent.VK_DELETE) || (txtNombrePlantilla.getText().length() >= 64 && c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombrePlantillaKeyTyped
    /*
    Vacia el area de texto de la plantilla.
    */
    private void btnLimpiarTextoPlantillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarTextoPlantillaMouseClicked
        txtAreaEscribirTextoPlantilla.setText("");
    }//GEN-LAST:event_btnLimpiarTextoPlantillaMouseClicked
    /*
    Vacia la caja de texto del nombre de la plantilla.
    */
    private void btnLimpiarNombrePlantillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarNombrePlantillaMouseClicked
        txtNombrePlantilla.setText("");
    }//GEN-LAST:event_btnLimpiarNombrePlantillaMouseClicked
    /*
    Si todo esta correcto crea o modifica la plantilla
    */
    private void btnAceptarPlantillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarPlantillaMouseClicked
        nuevaPlantilla();
        this.dispose();
    }//GEN-LAST:event_btnAceptarPlantillaMouseClicked
    /*
    Añade la variable al texto en la posicion que se encuentre en ese momento.
    */
    private void btnAddVariablePlantillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddVariablePlantillaMouseClicked
        txtAreaEscribirTextoPlantilla.insert(comboVariablesPlantilla.getSelectedItem().toString(), txtAreaEscribirTextoPlantilla.getCaretPosition());
    }//GEN-LAST:event_btnAddVariablePlantillaMouseClicked
    /*
    Dependiendo de la eleccion crea una nueva plantilla(0) o modifica la plantilla seleccionada(1).
    Cierra la ventana y muestra la tabla de plantilla actualizada situandose donde esté la nueva plantilla
    y mostrando la previw de ella.
    */
    public static void nuevaPlantilla() {
        if (!"".equals(txtNombrePlantilla.getText())) {
            if(empiezaPorLetra(txtNombrePlantilla.getText())==true){
                if (eleccion == 0) {
                    try {
                        conectar();
                        String sql = "INSERT INTO plantillas VALUES('" + txtNombrePlantilla.getText() + "','" + txtAreaEscribirTextoPlantilla.getText() + "');";
                        stmt.executeUpdate(sql);
                        c.commit();
                        desconectar();
                        mostrarTablaPlantillas();
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Ya existe una plantilla con ese nombre", "¡ATENCIÓN!", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    try {
                        borrarPlantilla(nombreP);
                        conectar();
                        String sql = "INSERT INTO plantillas VALUES('" + txtNombrePlantilla.getText() + "','" + txtAreaEscribirTextoPlantilla.getText() + "');";
                        if (auxBorrado == true) {
                            stmt.executeUpdate(sql);
                            auxBorrado = false;
                        }
                        c.commit();
                        desconectar();
                        mostrarTablaPlantillas();
                        tablaPlantillas.setRowSelectionInterval(buscarPlantilla(), buscarPlantilla());
                        scrollToSelectedRow(tablaPlantillas);
                        txtAreaPlantilla.setText((String) tablaPlantillas.getValueAt(tablaPlantillas.getSelectedRow(), 1));
                        
                    } catch (SQLException ex) {
                        //JOptionPane.showMessageDialog(null, "Ya existe una plantilla con ese nombre", "¡ATENCIÓN!", JOptionPane.ERROR_MESSAGE);
                        Logger.getLogger(Plantilla.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "El nombre no puede empezar por una letra", "¡ATENCIÓN!", JOptionPane.ERROR_MESSAGE);  
            }
        } else {
            JOptionPane.showMessageDialog(null, "El nombre no puede estar en blanco", "¡ATENCIÓN!", JOptionPane.ERROR_MESSAGE);
        }
    }
    /*
    Borra la plantilla seleccionada.
    */
    public static void borrarPlantilla(String plantilla) {
        try {
            conectar();
            String sql = "DELETE FROM plantillas WHERE nPlantilla='" + plantilla + "';";
            stmt.executeUpdate(sql);
            auxBorrado = true;
            c.commit();
            desconectar();
        } catch (SQLException ex) {
            Logger.getLogger(Plantilla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /*
    Busca una plantilla por su nombre.
    */
    public static int buscarPlantilla(){
        for(int i=0;i<tablaPlantillas.getRowCount();i++){
            String aux=(String)tablaPlantillas.getValueAt(i,0);
            if(aux.equals(txtNombrePlantilla.getText())){
                return i;
            }
        }
        return -1;
    }
    /*
    
    */
    public static void crearTablaPlantillas() {
        try {
            conectar();
            String sql = "CREATE TABLE IF NOT EXISTS plantillas "
                    + "(nPlantilla TEXT PRIMARY KEY NOT NULL,"
                    + "tPlantilla TEXT);";
            stmt.executeUpdate(sql);
            c.commit();
            desconectar();
        } catch (SQLException ex) {
            System.err.println("ERROR EN CREAR TABLA PLANTILLAS");
            Logger.getLogger(Envios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public static void dropPlantilla(){
        try {
            conectar();
            String sql="DROP TABLE IF EXISTS plantillas;";
            stmt.executeUpdate(sql);
            c.commit();
            desconectar();
        } catch (SQLException ex) {
            Logger.getLogger(Plantilla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void mostrarTablaPlantillas() {
            try {
                DefaultTableModel modelo = (DefaultTableModel) tablaPlantillas.getModel();
                for (int i = 0; i < tablaPlantillas.getRowCount(); i++) {
                    modelo.removeRow(i);
                    i -= 1;
                }
                conectar();
                String sql = "SELECT * FROM plantillas ORDER BY nPlantilla;";
                rs = stmt.executeQuery(sql);
                while (rs.next()) {
                    Object[] linea = new Object[2];
                    linea[0] = rs.getString("nPlantilla");
                    linea[1] = rs.getString("tPlantilla");
                    modelo.addRow(linea);
                }
                tablaPlantillas.setModel(modelo);
                desconectar();
                tablaPlantillas.getTableHeader().setBackground(colorAzul);
                tablaPlantillas.getTableHeader().setForeground(colorNegro);
                tablaPlantillas.getTableHeader().setFont(new Font("Tahoma",1,14));

            } catch (SQLException ex) {
                System.err.println("ERROR EN MOSTRAR Tabla plantillas");
                Logger.getLogger(Envios.class.getName()).log(Level.SEVERE, null, ex);
                System.exit(0);
            }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plantilla(eleccion, nombreP, textoP).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarPlantilla;
    private javax.swing.JButton btnAddVariablePlantilla;
    private javax.swing.JButton btnLimpiarNombrePlantilla;
    private javax.swing.JButton btnLimpiarTextoPlantilla;
    public static javax.swing.JComboBox<String> comboVariablesPlantilla;
    private javax.swing.JScrollPane jScrollPaneEscribirTextoPlantilla;
    private javax.swing.JLabel lblNombrePlantilla;
    private javax.swing.JPanel panelEscribirPlanilla;
    public static javax.swing.JTextArea txtAreaEscribirTextoPlantilla;
    public static javax.swing.JTextField txtNombrePlantilla;
    // End of variables declaration//GEN-END:variables
}
